config/routes.rb
PrintParlor::Application.routes.draw do
  root to: 'invitations#index'
  
  resources :invitations do 
    collection { get 'search' }
  end
  resources :menus do
    collection { get 'search'}
  end
  resources :programs do
    collection { get 'search'}
  end
  resources :save_the_dates do
    collection { get 'search'}
  end
  resources :rsvps do
    collection { get 'search'}
  end
  resources :thank_you_cards do
    collection { get 'search'}
  end
  resources :seasons do 
    collection { get 'search' }
  end
  resources :styles do 
    collection { get 'search' }
  end
  resources :colors do 
    collection { get 'search' }
  end
  resources :assets do 
    collection { get 'search' }
  end
  resources :invitation_pricings
  resources :pricing_cats
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :image_content_type, :image_file_name, 
                  :image_file_size, :image_updated_at, :name, :color_tokens,
                  :season_tokens, :style_tokens, :image
  
  has_many :program_colors
  has_many :colors, through: :program_colors
  
  has_many :program_seasons
  has_many :seasons, through: :program_seasons
  
  has_many :program_styles
  has_many :styles, through: :program_styles
  
  has_many :invitation_programs
  has_many :invitations, through: :invitation_programs
                  
  attr_reader :color_tokens, :season_tokens, :style_tokens

  def color_tokens=(ids)
    self.color_ids = ids.split(",")
  end

  def season_tokens=(ids)
    self.season_ids = ids.split(",")
  end

  def style_tokens=(ids)
    self.style_ids = ids.split(",")
  end

  has_attached_file :image, 
  	:styles => { :medium => "300x300>", 
  	  :grid => {:geometry => "1500x1500^", :format => :jpg}, 
  	  :thumb => {:geometry => "290x200>", :format => :jpg}},
  	  :large => {:geometry => "800x900"},
    	  :convert_options => {
    	    :grid => "-gravity southeast -extent 300x300",
    	    :thumb => "-quality 45 -strip"
    	  },

    :whiny => false,

    :storage => :s3,
    :s3_headers => { 'Content-Disposition' => 'inline' },
    :s3_credentials => (Rails.root + "config/s3.yml").to_s,
    :hash_data => ":attachment/:id/:style.:extension",
    :hash_secret => "longSecretString",
    :path => ":attachment/:id/:hash/:style.:extension"
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_filter :find_program, only: [:edit, :update, :show, :destroy]
  def index
    @programs = Program.all
  end

  def new
    @program = Program.new
  end
  
  def create
    @program = Program.new(params[:program])
    if @program.save
      redirect_to programs_path
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @program.update_attributes(params[:program])
      redirect_to programs_path
    else
      render 'edit'
    end
  end

  def show
  end
  
  def destroy
    @program.destroy
  end
  
  def search
    @programs = Program.all
    respond_to do |format|
      format.json { render json: Program.where("name like ?", "%#{params[:q]}%") }
    end
  end
  
  private
    def find_program
      @program = Program.find(params[:id])
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<div class="row">
    <div class="span8 offset2" id="program-form" 
                                data-colors-url="<%= search_colors_path %>.json"
                                data-styles-url="<%= search_styles_path %>.json"
                                data-seasons-url="<%= search_seasons_path %>.json"
                                data-assets-url="<%= search_assets_path %>.json">
                                
        <%= form_for @program, :html => { :multipart => true } do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :description %>
            <%= f.text_area :description %>
            
            <%= f.label :color_tokens %>
            <%= f.text_field :color_tokens, data: { load: @program.colors} %>
            
            <%= f.label :season_tokens %>
            <%= f.text_field :season_tokens, data: { load: @program.seasons } %>
            
            <%= f.label :style_tokens %>
            <%= f.text_field :style_tokens, data: { load: @program.styles} %>
            
            <%= f.file_field :image %>
            
            <%= f.submit class: 'btn btn-large btn-primary' %>
        <% end %>
    </div>
</div>

app/views/programs/_program.html.erb
<div class="span4">
    <%= link_to(image_tag(program.image.url(:thumb)),
        program.image.url(:original), :class => "thumbnail") %>
    <p class="invitation-title">
        <%= link_to "#{program.name}", program_path(program) %>
    </p>
    <p class="invitation-description">
        <%= link_to "#{program.description}", program_path(program) %>
    </p>
</div>

app/views/programs/edit.html.erb
<h1>Edit Program</h1>
<%= render 'form' %>

app/views/programs/index.html.erb
<h1>Programs</h1>
<div class="row">
    <%= render @programs %>
</div>

app/views/programs/new.html.erb
<h1>New Program</h1>
<%= render 'form' %>

app/views/programs/show.html.erb
<h1><%= @program.name %></h1>
<p><%= link_to @program.description, edit_program_path(@program) %></p>