config/routes.rb
PrintParlor::Application.routes.draw do
  root to: 'invitations#index'
  
  resources :invitations do 
    collection { get 'search' }
  end
  resources :menus do
    collection { get 'search'}
  end
  resources :programs do
    collection { get 'search'}
  end
  resources :save_the_dates do
    collection { get 'search'}
  end
  resources :rsvps do
    collection { get 'search'}
  end
  resources :thank_you_cards do
    collection { get 'search'}
  end
  resources :seasons do 
    collection { get 'search' }
  end
  resources :styles do 
    collection { get 'search' }
  end
  resources :colors do 
    collection { get 'search' }
  end
  resources :assets do 
    collection { get 'search' }
  end
  resources :invitation_pricings
  resources :pricing_cats
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  attr_accessible :description, :rsvpsimage_content_type, :rsvpsimage_file_name, 
                  :rsvpsimage_file_size, :rsvpsimage_updated_at, :name, :rsvpsimage, :color_tokens,
                  :season_tokens, :style_tokens
  
  has_many :rsvp_colors
  has_many :colors, through: :rsvp_colors
  
  has_many :rsvp_seasons 
  has_many :seasons, through: :rsvp_seasons
  
  has_many :rsvp_styles
  has_many :styles, through: :rsvp_styles
  
  has_many :invitation_rsvps
  has_many :invitations, through: :invitation_rsvps
                  
  attr_reader :color_tokens, :season_tokens, :style_tokens, :asset_tokens

  def color_tokens=(ids)
    self.color_ids = ids.split(",")
  end

  def season_tokens=(ids)
    self.season_ids = ids.split(",")
  end

  def style_tokens=(ids)
    self.style_ids = ids.split(",")
  end

  def asset_tokens=(ids)
    self.asset_ids = ids.split(",")
  end

  has_attached_file :rsvpsimage, 
  	:styles => { :medium => "300x300>", 
  	  :grid => {:geometry => "1500x1500^", :format => :jpg}, 
  	  :thumb => {:geometry => "290x200>", :format => :jpg}},
  	  :large => {:geometry => "800x900"},
    	  :convert_options => {
    	    :grid => "-gravity southeast -extent 300x300",
    	    :thumb => "-quality 45 -strip"
    	  },

    :whiny => false,

    :storage => :s3,
    :s3_headers => { 'Content-Disposition' => 'inline' },
    :s3_credentials => (Rails.root + "config/s3.yml").to_s,
    :hash_data => ":attachment/:id/:style.:extension",
    :hash_secret => "longSecretString",
    :path => ":attachment/:id/:hash/:style.:extension"
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_filter :find_rsvp, only: [:edit, :update, :show, :destroy]
  def index
    @rsvps = Rsvp.all
  end

  def new
    @rsvp = Rsvp.new
  end
  
  def create
    @rsvp = Rsvp.new(params[:rsvp])
    if @rsvp.save
      redirect_to rsvps_path
    else
      render 'edit'
    end
  end

  def edit
  end
  
  def update
    if @rsvp.update_attributes(params[:rsvp])
      redirect_to rsvps_path
    else
      render 'edit'
    end
  end

  def show
  end
  
  def destroy
    @rsvp.destroy
  end
  
  def search
    @rsvps = Rsvp.all
    respond_to do |format|
      format.json { render json: Rsvp.where("name like ?", "%#{params[:q]}%") }
    end
  end
  
  private
  
    def find_rsvp
      @rsvp = Rsvp.find(params[:id])
    end
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/views/rsvps/_form.html.erb
<div class="row">
    <div class="span8 offset2" id="rsvp-form" 
                                data-colors-url="<%= search_colors_path %>.json"
                                data-styles-url="<%= search_styles_path %>.json"
                                data-seasons-url="<%= search_seasons_path %>.json"
                                data-assets-url="<%= search_assets_path %>.json">
                                
        <%= form_for @rsvp, :html => { :multipart => true } do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :description %>
            <%= f.text_area :description, class: "shortbox" %>
            
            <%= f.label :color_tokens, "Colors" %>
            <%= f.text_field :color_tokens, data: { load: @rsvp.colors} %>
            
            <%= f.label :season_tokens, "Seasons" %>
            <%= f.text_field :season_tokens, data: { load: @rsvp.seasons } %>
            
            <%= f.label :style_tokens, "Styles" %>
            <%= f.text_field :style_tokens, data: { load: @rsvp.styles} %>
            
            <%= f.file_field :rsvpsimage %>
            
            <%= f.submit class: 'btn btn-large btn-primary' %>
        <% end %>
    </div>
</div>

app/views/rsvps/_rsvp.html.erb
<div class="span4 gridview">
    <%= link_to(image_tag(rsvp.rsvpsimage.url(:thumb)),
        rsvp.rsvpsimage.url(:original), :class => "thumbnail") %>
    <p class="invitation-title">
        <%= link_to "#{rsvp.name}", rsvp_path(rsvp) %>
    </p>
    <p class="invitation-description">
        <%= link_to "#{rsvp.description}", rsvp_path(rsvp) %>
    </p>
</div>

app/views/rsvps/edit.html.erb
<h1>Edit RSVP</h1>
<%= render 'form' %>

app/views/rsvps/index.html.erb
<h1>RSVP's</h1>
<div class="row">
    <%= render @rsvps %>
</div>

app/views/rsvps/new.html.erb
<h1>New RSVP</h1>
<%= render 'form' %>

app/views/rsvps/show.html.erb
<h1><%= @rsvp.name %></h1>
<p><%= link_to @rsvp.description, edit_program_path(@rsvp) %></p>