config/routes.rb
PrintParlor::Application.routes.draw do
  root to: 'invitations#index'
  
  resources :invitations do 
    collection { get 'search' }
  end
  resources :menus do
    collection { get 'search'}
  end
  resources :programs do
    collection { get 'search'}
  end
  resources :save_the_dates do
    collection { get 'search'}
  end
  resources :rsvps do
    collection { get 'search'}
  end
  resources :thank_you_cards do
    collection { get 'search'}
  end
  resources :seasons do 
    collection { get 'search' }
  end
  resources :styles do 
    collection { get 'search' }
  end
  resources :colors do 
    collection { get 'search' }
  end
  resources :assets do 
    collection { get 'search' }
  end
  resources :invitation_pricings
  resources :pricing_cats
end

app/models/thank_you_card.rb
class ThankYouCard < ActiveRecord::Base
  attr_accessible :description, :name, :tyimage_content_type, :tyimage_file_name, 
                  :tyimage_file_size, :tyimage_updated_at, :color_tokens, 
                  :season_tokens, :style_tokens, :tyimage
                  
  has_many :invitation_thank_you_cards
  has_many :invitations, through: :invitation_thank_you_cards
  
  has_many :thank_you_card_colors
  has_many :colors, through: :thank_you_card_colors
  
  has_many :thank_you_card_seasons
  has_many :seasons, through: :thank_you_card_seasons
  
  has_many :thank_you_card_styles
  has_many :styles, through: :thank_you_card_styles
                  
  attr_reader :color_tokens, :season_tokens, :style_tokens

  def color_tokens=(ids)
    self.color_ids = ids.split(",")
  end

  def season_tokens=(ids)
    self.season_ids = ids.split(",")
  end

  def style_tokens=(ids)
    self.style_ids = ids.split(",")
  end

  has_attached_file :tyimage, 
  	:styles => { :medium => "300x300>", 
  	  :grid => {:geometry => "1500x1500^", :format => :jpg}, 
  	  :thumb => {:geometry => "290x200>", :format => :jpg}},
  	  :large => {:geometry => "800x900"},
    	  :convert_options => {
    	    :grid => "-gravity southeast -extent 300x300",
    	    :thumb => "-quality 45 -strip"
    	  },

    :whiny => false,

    :storage => :s3,
    :s3_headers => { 'Content-Disposition' => 'inline' },
    :s3_credentials => (Rails.root + "config/s3.yml").to_s,
    :hash_data => ":attachment/:id/:style.:extension",
    :hash_secret => "longSecretString",
    :path => ":attachment/:id/:hash/:style.:extension"
end

app/controllers/thank_you_cards_controller.rb
class ThankYouCardsController < ApplicationController
  before_filter :find_thank_you_card, only: [:edit, :update, :show, :destroy]
  def index
    @thank_you_cards = ThankYouCard.all
  end
  
  def new
    @thank_you_card = ThankYouCard.new
  end
  
  def create
    @thank_you_card = ThankYouCard.new(params[:thank_you_card])
    if @thank_you_card.save
      redirect_to thank_you_cards_path
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @thank_you_card.update_attributes(params[:thank_you_card])
      redirect_to thank_you_cards_path
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @thank_you_card.destroy
  end
  
  def search
    @thank_you_cards = ThankYouCard.all
    respond_to do |format|
      format.json { render json: ThankYouCard.where("name like ?", "%#{params[:q]}%") }
    end
  end
  
  private
    def find_thank_you_card
      @thank_you_card = ThankYouCard.find(params[:id])
    end
end

app/helpers/thank_you_cards_helper.rb
module ThankYouCardsHelper
end

app/views/thank_you_cards/_form.html.erb
<div class="row">
    <div class="span8 offset2" id="thank-you-card-form" 
                                data-colors-url="<%= search_colors_path %>.json"
                                data-styles-url="<%= search_styles_path %>.json"
                                data-seasons-url="<%= search_seasons_path %>.json">
                                
        <%= form_for @thank_you_card, :html => { :multipart => true } do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :description %>
            <%= f.text_area :description, class: "shortbox" %>
            
            <%= f.label :color_tokens, "Colors" %>
            <%= f.text_field :color_tokens, data: { load: @thank_you_card.colors} %>
            
            <%= f.label :season_tokens, "Seasons" %>
            <%= f.text_field :season_tokens, data: { load: @thank_you_card.seasons } %>
            
            <%= f.label :style_tokens, "Styles" %>
            <%= f.text_field :style_tokens, data: { load: @thank_you_card.styles} %>
            
            <%= f.file_field :tyimage %>
            
            <%= f.submit class: 'btn btn-large btn-primary' %>
        <% end %>
    </div>
</div>

app/views/thank_you_cards/_thank_you_card.html.erb
<div class="span4">
    <%= link_to(image_tag(thank_you_card.tyimage.url(:thumb)), 
        thank_you_card.tyimage.url(:original), :class => "thumbnail") %>
    <p class="invitation-title">
        <%= link_to "#{thank_you_card.name}", thank_you_card_path(thank_you_card) %>
    </p>
    <p class="invitation-description">
        <%= link_to "#{thank_you_card.description}", thank_you_card_path(thank_you_card) %>
    </p>
</div>

app/views/thank_you_cards/edit.html.erb
<h1>Edit Thank You Card</h1>
<%= render 'form' %>

app/views/thank_you_cards/index.html.erb
<h1>Thank You Cards</h1>
<div class="row">
    <%= render @thank_you_cards %>
</div>

app/views/thank_you_cards/new.html.erb
<h1>New Thank You Card</h1>
<%= render 'form' %>

app/views/thank_you_cards/show.html.erb
<h1><%= @thank_you_card.name %></h1>
<p><%= link_to @thank_you_card.description, edit_thank_you_card_path(@thank_you_card) %></p>