config/routes.rb
PrintParlor::Application.routes.draw do
  root to: 'invitations#index'
  
  resources :invitations do 
    collection { get 'search' }
  end
  resources :menus do
    collection { get 'search'}
  end
  resources :programs do
    collection { get 'search'}
  end
  resources :save_the_dates do
    collection { get 'search'}
  end
  resources :rsvps do
    collection { get 'search'}
  end
  resources :thank_you_cards do
    collection { get 'search'}
  end
  resources :seasons do 
    collection { get 'search' }
  end
  resources :styles do 
    collection { get 'search' }
  end
  resources :colors do 
    collection { get 'search' }
  end
  resources :assets do 
    collection { get 'search' }
  end
  resources :invitation_pricings
  resources :pricing_cats
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name
  default_scope order("colors.name ASC")
  has_many :invitation_colors
  has_many :invitations, through: :invitation_colors
  
  has_many :menu_colors
  has_many :menus, through: :menu_colors
  
  has_many :program_colors
  has_many :programs, through: :program_colors
  
  has_many :save_the_date_colors
  has_many :save_the_dates, through: :save_the_date_colors
  
  has_many :rsvp_colors
  has_many :rsvps, through: :rsvp_colors
  
  has_many :thank_you_card_colors
  has_many :thank_you_cards, through: :thank_you_card_colors
  
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_filter :find_color, only: [:show, :edit, :update, :destroy]
  def index
    @colors = Color.all
  end

  def new
    @color = Color.new
  end
  
  def create
    @color = Color.new(params[:color])
    if @color.save
      redirect_to colors_path
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @color.update_attributes(params[:color])
      redirect_to colors_path
    else
      render 'edit'
    end
  end

  def show
    @rsvp_pricing = RsvpPricing.all
  end
  
  def destroy
    @color.destroy
  end
  
  def search
    @colors = Color.all
    respond_to do |format|
      format.json { render json: Color.where("name like ?", "%#{params[:q]}%") }
    end
  end
  
  private
    def find_season
      @color = Color.find(params[:id])
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_color.html.erb
<p><%= link_to color.name, color_path(color) %></p>

app/views/colors/_form.html.erb
<div class="row">
    <div class="span8 offset2">
        <%= form_for @color do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.submit class: 'btn btn-large btn-primary' %> 
        <% end %>
    </div>
</div>

app/views/colors/edit.html.erb
<h1>Edit Color</h1>
<%= render 'form' %>

app/views/colors/index.html.erb
<h1>Styles</h1>
<div class="row">
    <div class="span8 offset2">
        <p><%= link_to "New Color", new_color_path, class: 'btn btn-large btn-primary' %></p>
        <%= render @colors %>
    </div>
</div>

app/views/colors/new.html.erb
<h1>New Color</h1>
<%= render 'form' %>

app/views/colors/show.html.erb
<h1><%= link_to @color.name, edit_color_path(@color) %></h1>